// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/world": {
    params: {};
  };
  "/arcade": {
    params: {};
  };
  "/observatory": {
    params: {};
  };
  "/radio": {
    params: {};
  };
  "/garden": {
    params: {};
  };
  "/camera": {
    params: {};
  };
  "/archive": {
    params: {};
  };
  "/secret": {
    params: {};
  };
  "/universe": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/world" | "/arcade" | "/observatory" | "/radio" | "/garden" | "/camera" | "/archive" | "/secret" | "/universe";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/world.tsx": {
    id: "routes/world";
    page: "/world";
  };
  "routes/arcade.tsx": {
    id: "routes/arcade";
    page: "/arcade";
  };
  "routes/observatory.tsx": {
    id: "routes/observatory";
    page: "/observatory";
  };
  "routes/radio.tsx": {
    id: "routes/radio";
    page: "/radio";
  };
  "routes/garden.tsx": {
    id: "routes/garden";
    page: "/garden";
  };
  "routes/camera.tsx": {
    id: "routes/camera";
    page: "/camera";
  };
  "routes/archive.tsx": {
    id: "routes/archive";
    page: "/archive";
  };
  "routes/secret.tsx": {
    id: "routes/secret";
    page: "/secret";
  };
  "routes/universe.tsx": {
    id: "routes/universe";
    page: "/universe";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/world": typeof import("./app/routes/world.tsx");
  "routes/arcade": typeof import("./app/routes/arcade.tsx");
  "routes/observatory": typeof import("./app/routes/observatory.tsx");
  "routes/radio": typeof import("./app/routes/radio.tsx");
  "routes/garden": typeof import("./app/routes/garden.tsx");
  "routes/camera": typeof import("./app/routes/camera.tsx");
  "routes/archive": typeof import("./app/routes/archive.tsx");
  "routes/secret": typeof import("./app/routes/secret.tsx");
  "routes/universe": typeof import("./app/routes/universe.tsx");
};